### ISSUE TITLE
Question about util.project_xy()

### ISSUE THREAD

**Issue by genevieve-le-houx** [PRBonn/pole-localization#5]
Hi,

First, Thank you for the excellent work!

I've been trying to understand the work done in src/ncltpoles

**util.poject_xy()**
I have a question regarding the function util.project_xy(). I don't really understand what transformation it's achieving ? 

**ncltpoles.save_local_maps()**
Also, in the function ncltpoles.save_local_maps(), I don't understand why we need to do 

`T_w_mc = util.project_xy(session.T_w_r_odo_velo[imid[i]].dot(T_r_mc))`

Couldn't we simply have done 

`T_w_mc = session.T_w_r_odo_velo[imid[i]].dot(T_r_mc) ` ? 

And why `T_m_r` couldn't simply be `T_m_r = T_m_mc.dot(T_mc_r)` ?

Thanks,

**Comment by donghao51** [comment]
Hello, sorry for the late response.

util.project_xy() is used to project the original 3-dim transformation to the 2-dim since our work only focuses on localization in 2D space. 

Yes, we can calculate `T_m_r = T_m_mc.dot(T_mc_r)` as in https://github.com/PRBonn/pole-localization/blob/96f15f8125e8b78da8282c4be127385ada3410a0/src/ncltpoles.py#L29.
But in save_local_maps() we use `T_m_r = np.matmul(T_m_w, T_w_r) ` because the calculation of T_m_w and T_w_r is more straightforward.
